### ISSUE TITLE
Prototyping toggle button to have basic/advanced Boosted documentation

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1505]
Boosted is a fork of Bootstrap so we gather all its features (components and utilities) and documentation, and then adapt it to develop our Orange Design System.

It has some drawbacks in our Boosted documentation since some elements become not compliant with our own design system:
- Few components
- Few variants of those components
- Some examples
- Some utilities in certain context

This issue proposes to prototype a toggle button in the documentation to have:
- a **basic** documentation containing only things compliant with the design system
- an **advanced** documentation containing all technical things present in our framework (basically the content of our current documentation)

The challenge here is to be able to remove things dynamically from the documentation by identifying in the Markdown elements that must be hidden:
- Entire side menu item (page)
- Entire right menu item (anchor link in a page)
- Part of a section
- Example(s) amongst other examples (and associated code)

**Side note**: how to keep the context of this mode while navigation and what do we do of links to https://boosted.orange.com/docs/5.2/components/badge/ in a paragraph if they are not available for basic usage.

**Comment by MewenLeHo** [comment]
Some comments based on my current investigation, felle free to have look on [Hugo's documentation](https://gohugo.io/) to confirm and/or make suggestions and join the taskforce on this huge topic. No jokes it really is a huge topic, we need people.

My first thought was to use the [conditionnal logic of Hugo](https://gohugo.io/templates/introduction/#conditionals):

You will need to add a page parameter like:
`basic: true`

Then it will be possible to do something like:
```
{{< doc.inline >}}
{{ if .Page.Params.basic}}
// Basic documentation
{{ else }}
// Advanced documentation
{{ end }}
{{< /doc.inline >}}
```

The problem here is will it be possible to update dynamically a parameter by using js for instance and generate a new template file on the fly? 
If yes, perfect.
If not then we need to find another solution.

Another way to achieve it will be to simply wrap all elements in a CSS class 'basic' or 'advanced' and toggle it in JS. Simpler but the high maintenance cost is a huge drawback.

Third possibilty: separate all elements in multiples templates. Once again the maintenance cost may be a problem. In the size of the bundle may also be a problem.

Last possibility for now: it seems that Hugo added [render hooks in the latest versions ](https://gohugo.io/templates/render-hooks/#readout) but we still need to figure out how it works.

*** Complementary informations ***

This topic is not just about basic/advanced documentation. We will also need it to generate a different documentation for the incoming different themes (6 themes).
And some parts of the doc can be basic for one theme but advanced for the others so we need to be able to handle endless combinations.

Please note that we also need to pay attention to accessibility and code validation. For instance, we may need to have two `<h1>` (one in the basic part and the second one in the advanced part) or multiple element with the same `id`. Duplicate content will also be a major issue.

**Comment by MewenLeHo** [comment]
Maybe a starting point, using Hugo and Middleman:
[https://github.com/gohugoio/hugo/issues/140](https://github.com/gohugoio/hugo/issues/140)
[https://middlemanapp.com/advanced/dynamic-pages](https://middlemanapp.com/advanced/dynamic-pages)
