### ISSUE TITLE
Dropdown focus and mouseover

### ISSUE THREAD

**Issue by liyokuna** [Orange-OpenSource/Orange-Boosted-Bootstrap#158]
Hey !
When the mouse goes over element inside the dropdown their background color become black. Whereas when you navigate using your keyboard, the background doesn't change.
Here is a link to the [dropdown](https://boosted.orange.com/docs/4.3/components/dropdowns/#single-button).
It will more convenient to have the same behaviour when focusing or hovering.
@PigeardSylvain

**Comment by ffoodd** [comment]
@Lausselloic @PigeardSylvain I did change this, but this all went from a Boosted override: FYI, it was probably meant to have a separate hover & focus style… But this was done very weirdly.

The only reason I see to do that is to avoid the firs tfocus style: opening dropdown gives focus to first dropdown item, thus higlight it directly. I personnaly think this is all good, but I guess it might scare a few designers…

Any thought on this? 

I did this precisely so reverting it would be easy.

**Comment by Lausselloic** [comment]
yes it was force in boosted to focus first element because it's link to the way boosted add aria-* on dropdown elements : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/js/src/dropdown.js#L374

It's not the way it's done in bootstrap, and maybe need to be discuss with @Aniort 
If we came back to bootstrap style without role menu, I think there's no need to focus first element when opening dropdown, but there's a need to improve focus style to meet the brand requirement (white text on black background)
