### ISSUE TITLE
Supra bars: spacing on small viewports

### ISSUE THREAD

**Issue by louismaximepiton** [Orange-OpenSource/Orange-Boosted-Bootstrap#1673]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Spacing between the links in small viewports seems to be a bit too small.

![image](https://user-images.githubusercontent.com/91960143/204853294-c261c956-87c5-4a6c-9804-aefd4e366f79.png)

### Reduced test cases

Go on https://main--boosted.netlify.app/docs/5.2/components/orange-navbar/#example and reduce the screen until the medium breakpoint.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Boosted are you using?

5.2.2 (current_main_branch)

**Comment by sharmadhiraj86** [comment]
I would like to contribute to the issue can you let me know how i can solve the issue.

**Comment by julien-deramond** [comment]
Hey @sharmadhiraj86 
Thanks for the interest. You can provide a PR to tackle this issue but unfortunately we won't have time to let you know how you can solve the issue. Otherwise, it would have been already fixed.
The objective is to respect [these design guidelines](https://system.design.orange.com/0c1af118d/p/37609b-global-headers/b/366c91/i/66611060) without breaking what's already in place.
Might not be an easy one.
