### ISSUE TITLE
Question about the compliance for opensource of the font HelvNeue

### ISSUE THREAD

**Issue by LudovicSoltysOAB** [Orange-OpenSource/Orange-Boosted-Bootstrap#334]
Hi,

I'm currently working on a project that embeds Orange Boosted, and we would like to publish it on GitHub. We use Fossology so as to validate the licenses of our project.

But Fossology has noticed that we use HelvNeue TTF font that seems to be commercial. This font is included in Orange Boosted, and i would like to know how to solve this problem. 

Could you tell me why the dist embeds that files ? and can I just remove the ttf files, or do i need to do something special about my fonts ?

Regards,
Ludovic

**Comment by Lausselloic** [comment]
Hello,

If your project is for Orange usage and need to use Helvetica font you could keep it in your repo but add a notice file like in boosted to explain taht some component are not under your project main license e.g MIT for boosted https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/NOTICE.txt it's the case for Orange logo and helvetica font that Orange paid to use for it's website but other project need to buy a license.

If your project is not for Orange you could remove Helvetica files and orangeHelvetica.css files and of course don't load that file in your source code.

As explain in the sample template https://boosted.orange.com/docs/4.4/getting-started/introduction/#starter-template helvetica and icons are only for Orange use.

To resume, it's normal that Fossology notice you, but if you don't use the font into your project there's no problem, otherwise put a notice.txt file

**Comment by LudovicSoltysOAB** [comment]
Thank you for your answer. No, my project is not for Orange only. So i'll remove the files.

I'm no expert with css. Do I also have to remove the font family "HelvNeueOrange, Helvetica Neue, Helvetica" that are witten in the CSS files ?

**Comment by Lausselloic** [comment]
No you could let declarations into the css, the browser will fall back to Helvetica font if installed on OS or Arial

**Comment by ffoodd** [comment]
@LudovicSoltysOAB Just to clarify, you do not need the Orange brand at all?

If so — and if @Lausselloic answer is enough, may I close this issue?
