### ISSUE TITLE
v4.5.0 - Bug with tab (responsive)

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#456]
Hello

We recently observed a bug with last version of Boosted (v4.5.0) regarding tab : 
https://boosted.orange.com/docs/4.5/boostwatch/#tab

If you reduce the width of the screen (to simulate responsive approach), at one point, the display is broken (cf. screenshot below) 

![image](https://user-images.githubusercontent.com/63303383/89657816-fa73a680-d8cd-11ea-97ac-0eaa91fd58ee.png)

Do you have an idea how we could avoid such behavior  ? Thank you for your feedback

**Comment by ffoodd** [comment]
Hi there,

[This behaviour directly comes from Bootstrap](https://getbootstrap.com/docs/4.5/components/navs/#tabs). [As mentionned in both docs](https://boosted.orange.com/docs/4.5/components/navs/#working-with-flex-utilities) you may use flex utilities to change the responsive behaviour, you'd then need to play a bit with custom styles to handle borders.

You could also prevent wrapping using `.flex-nowrap` and enforce `overflow` to be scrollable with `auto`, as it's a pretty common pattern now.

Boosted v4 also has [a custom `o-tab` component](https://boosted.orange.com/docs/4.5/components/navs/#responsive-tabs) to switch from tabs to accordions on small screen, but it's far from ideal and will be completely refactored in v5. It has several issues open that'll be tackled in v5: #150 and #140 — so use it carefully.

I'm closing this — since there's not much I can do — but referencing it in already opened issue for the records :)
