### ISSUE TITLE
<Component> is transitioning

### ISSUE THREAD

**Issue by CorentinHcd** [Orange-OpenSource/Orange-Boosted-Bootstrap#50]
Hello,

We are waiting for [this fix](https://github.com/twbs/bootstrap/pull/21743) to be merged on Bootstrap, so i'm opening a ticket on Boosted to know if it can be merged after and to know the version of Boosted with the correction.

Have a good day,
Corentin

**Comment by Lausselloic** [comment]
Hi,

We're following all bootstrap release as quick as possible. So if the fix is merge in bootstrap for v4.beta it will be in the boosted v4.beta also.

We will create intermediate boosted release v4.alpha.6.1 soon, and merge current bootstrap v4-dev onto boosted, so if the fix is already merge it will be in boosted alpha.6.1. 

I will let you know when it's done.

**Comment by Lausselloic** [comment]
Fix merged from bootstrap in v4.0.0-alpha.6.1

**Comment by KimberleyG** [comment]
Hello, 
We are facing another issue on our application, but related this time to modals (we have the error "Modal is transitioning"). But the code merged from Boostrap in the [commit](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/bb16f7609121716ce96b31340e82651bcbe8dee1) doesn't include files related to modal (modal.js and modal.html).

I've seen that this code will be available in beta version but is it possible to have an intermediate alpha version with this code?

Thanks in advance,
Kimberley
