### ISSUE TITLE
Incoherent colors and class names

### ISSUE THREAD

**Issue by ojaulent** [Orange-OpenSource/Orange-Boosted-Bootstrap#610]
Hi,

Since version 4.5, badge and background colors changed.
These components now use _Orange Supporting colors_ instead of _Orange Functional colors_.
The CSS classe names, are still the same, they look like *-danger, *-warning, etc.

The first problem : now there is a color incoherence with other classes with similar names.
The other problem is the meaning of the class names do not correspond with the color.

Example : 
- badge-**danger** and background-**danger** are now in **pink** (#ffb4e6)
- BUT border-**danger**, btn-**danger**, alert-**danger** are still in **red** (#cd3c14)
- How something called **danger** be in **pink** ?

Can we have an harmonization of colors ?
Like keeping all standard bootstrap classes in _Orange Functional colors_ and adding few classes for Supporting colors ?

Regards,

Olivier

**Comment by ffoodd** [comment]
Just pasting my first answer here for tracking, question asked to the brand to decide if we stick to the current state or if we follow your suggestion and provide both color set.

---

As explained in Orange's Web Browsing Guidelines:

> Functional colours can be used for certain functions in places where there are strongly established conventions. Functional colours are associated with specific meanings:
- Green for success.
- Blue for information and discovery.
- Yellow for warning or alert.
- Red for critical.

Badges are mostly used for tags (e.g. categories in a CMS) or flags (e.g. "NEW" in a product title), unrelated to the specific meanings attached to functional colors. Supporting colors are meant to be used as background, so here they are.

Regarding naming, please keep in mind that Boosted is built on top of Bootstrap: we don't rename Bootstrap components nor do we rename their variants.

**Comment by ffoodd** [comment]
Hi there,

Got an answer from our brand:
- regarding badges, functional colors should be used . Badges are in UI Kit's backlog and considered as functional components, so my interpretation of the Web Browsing Guidelines was wrong here.
- regarding backgrounds, functional colors are strictly forbidden: what can be done here is to keep the current naming (to keep Bootstrap interoperability) but also alias those to use color related naming (and add those to the docs, obviously).

Let's go!

**Comment by ojaulent** [comment]
Hi,

**Thanks a lot for badges**, it will be better for our team.

Regarding to backgrounds : I understand that a global background in a _Functional color_ is forbidden, but : 
- CSS classes of background can be used for some custom functional component (background-* classes can be applied anywhere in a html template)
- because of the class names, if background keep Supporting color but use functionnal names (eg. *-danger) it will be confusing.

So, **can you re-evaluate my proposal** : keep all standard bootstrap classes in _Orange Functional colors_ and adding few classes for _Supporting colors_ ?

Thanks again,
Olivier

**Comment by ffoodd** [comment]
As I said, functional colors are forbidden for background. And I can't obviously drop background utilities with functional names for backward compatibility. The best I can do here is to un-document background utilities with functional names and only document those with supporting color names.

But `.bg-danger` would still be pink, and there's not much I can do for it.

FWIW, naming consistency cannot be a requirement in Boosted since naming mostly comes from Bootstrap and is not meant to be consistent with our Web UI Kit.

**Comment by ojaulent** [comment]
> As I said, functional colors are forbidden for background.

But buttons (an badges in the future) have functional color for background !

> naming consistency cannot be a requirement in Boosted

How can we use a library where **one** suffix name is corresponding to **two** colors ?
And where that **two** colors have **two** different meaning !
Sorry, but it breaks all (my) logic.

**Comment by ffoodd** [comment]
Well, to quote directly the answer I had:
> We do not currently use the functional colours as a general background colour. We only use them for components, icons or possibly data displays. You can use supporting colours as background colour for illustrations or info graphics.

At the moment, the only cases were functional colors are appropriate as backgrounds are components delivered in the Web UI Kit. In other words, there's no case in Boosted where someone should need functional color as background, since Boosted should have implemented every case in its core components.

It's not a matter of logic, you need to understand the constraints around this whole project: we're implementing Orange brand Web UI Kit **and** staying backward compatible with Bootstrap. It's obviously not always consistent.

As I said, what I'm about to do is to un-document background utilities using `success` et all and replace them with more consistent naming. However Bootstrap classes still need to work.

**Comment by ojaulent** [comment]
I understand that's not your decision and that you do your best.
I remain disagree with it and I hope it won't affect usability of the Boosted library.

Thank you for your time.

Regards
Olivier
