### ISSUE TITLE
improve boosted print mode

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#86]
When printing some boosted component, background color and icons disapear.

Need to identify why and try to improve it

[Boostwatch · Boosted.pdf](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/files/2084464/Boostwatch.Boosted.pdf)

**Comment by ygatesoupe** [comment]
Not printing background is default behaviour for browsers. 

There is no cross-browser solution and fixing this can get hacky. 

Easiest way is to configure the browser print options (here in Firefox) :

![print](https://user-images.githubusercontent.com/15139360/41220652-55f61a4e-6d62-11e8-8103-3f447ae2b005.png)

[Boostwatch · Boosted.pdf](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/files/2089210/Boostwatch.Boosted.pdf)

**Comment by Lausselloic** [comment]
Yes quite okay for Chrome, but here are the main problem on Firefox59 and IE11, not all the page was printed only 1 page. 
Maybe need to check if it's related to a browser bug.
![capture firefox](https://user-images.githubusercontent.com/11272238/41342265-2078966c-6efc-11e8-898a-a59202ae943b.PNG)
![capture ie11](https://user-images.githubusercontent.com/11272238/41342266-20a18496-6efc-11e8-84cb-98df2ebcc275.PNG)

**Comment by liyokuna** [comment]
Hello @Lausselloic I looked around on the internet and I found out that the issue you raise, happens only on Firefox and IE11.
[As mentioned here](https://support.mozilla.org/fr/questions/1100801), for firefox, the reason is that developers focus on a proper screen rendering than proper pagination for print out.
Concerning IE11, there is a lot of solutions but none of them have worked on my computer. 
This is one of hte most shared [fixed](https://answers.microsoft.com/en-us/ie/forum/ie11-windows_7/ie11-cant-print-web-pages/6176b43c-273f-4a00-9acc-b8f65f9c603f).

**Comment by Lausselloic** [comment]
I've try to fix it, and test on boosted documentation for v4.2 looks like to be better : 
https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/267ac60e6c176ea57eaec18fd448e8fbd3449f23

Juste add a display:block for printing on .row and form-row class. Looks beter but not perfect.
