### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#892]
# Footer

## Description

Footer module is a combination of different sub-elements that can compose a footer:
- Terms & Conditions
- Navigation
- Follow us bar
- Email sign up
- Service links

## References

**Orange Design System**: [Modules > Footer](https://system.design.orange.com/0c1af118d/p/20e9fb-footer/b/9571c3)

## Development

- [x] Study the architecture of this module. It will probably be a responsive `<footer>` container that can be composed of different sub-elements.
  - Do we need to create a specific component? Or could it be just [examples as it is done in Bootstrap](https://getbootstrap.com/docs/5.1/examples/footers/)?
- [ ] Replace the ephemeral content developed in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/922
- [ ] Footer > Terms & Conditions
- [ ] Footer > Navigation
- [ ] Footer > Follow Us Bar
- [ ] Footer > Email Sign Up
- [ ] Footer > Service Links

**Comment by louismaximepiton** [comment]
WIP on footers on this [CodePen](https://codepen.io/louismaximepiton/pen/jOLYgxW?editors=1100).

Good points I noticed : 
- Not that far from the design specifications.
- Very few changes to bring to Boosted (only one example to add).
- Responsive footer.

Bad points I noticed yet : 
- It uses homemade dark versions of components (buttons, accordion, input, ...).
- Border color is 666 rather than 333. Need one utility more.
- Margins and paddings aren't responsive due to utilities.
- Need Js for accordions.
- Dark versions of buttons, accordion and input don't follow the design specs atm.

Not related : 
- Coverage icon not centered.
