### ISSUE TITLE
stepbar : error on the last element if the current

### ISSUE THREAD

**Issue by jo6891** [Orange-OpenSource/Orange-Boosted-Bootstrap#9]
stepbar : there is an error on the last element if the current and the screen size is less than 980px .
The arrow appears and the background is too small.

to easily solve : 
```
.o-stepbar .stepbar-item.current:last-child::after {
    display: none;
}

@media (min-width: 768px) and (max-width: 980px) {
    .o-stepbar .stepbar-item.current:last-child {
        width: inherit;
        padding: 1.2rem 1rem 1.2rem 2.6rem;
    }
}

![capture2](https://cloud.githubusercontent.com/assets/4937742/18556613/3097d9a2-7b6c-11e6-95de-66d091c6f26a.PNG)
![capture1](https://cloud.githubusercontent.com/assets/4937742/18556614/309a9426-7b6c-11e6-9d88-b009a5ae240f.PNG)

```

**Comment by ygatesoupe** [comment]
Fixed hide last item arrow display for each state in commit 52405a93849528f18b852a95353a3fa8040be4a3

In the provided screenshots it seems that your using auto width for step items. This is not intended behaviour, each item has equal width, which is set in css according to the number items in the stepbar, so that the stepbar always take full width of its container.
