### ISSUE TITLE
Components with dark background

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#917]
Components with dark background are needed in Boosted.
This story is a 2-steps story:
- [x] Study how to integrate components with dark background (see https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/957)
- [x] Apply it to existing components in v5
  - [x] Links, code and default elements
  - [x] Accordions
  - [x] Alerts
  - [x] Buttons
  - [x] Dropdowns    

Some stories probably linked:
- https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/713
- https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/657
- https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/511
- https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/117

**Comment by MewenLeHo** [comment]
After the meeting made today, we agreed that : 
- there are so many solutions to do to that.
- We may have find the best solution but we need more time to figure out exactly how to implement it correctly.
- We can't take the risk to do something before Bootstrap. If we take a different decision the gap between Bootstrap and Boosted will be too bid and Boosted will become more difficult to maintain since merging the code may become painful.

So we decided to keep tracks of everything (including the specific discussion channel and the branch) and to keep an eye on this feature in the next version of Boostrap.

By then we are more than welcome to offer our help, take part at the discussion, test a new idea,...

**Comment by ffoodd** [comment]
Great to see this finally happening :tada:

FYI [Mark started something based on custom properties and `data-theme` attribute](https://github.com/twbs/bootstrap/pull/35857/files): only a draft for now but I suggest you have a look at it and maybe wait for Bootstrap's implementation?

Anyway, I really hope you'll take some time to review their draft and make some useful comments, since you already have some experience around dark theme :)

**Comment by julien-deramond** [comment]
The components planned for this user story has been developed. If needed we will open up a new issue to track the new dark variant needed in Boosted.

@ffoodd I keep in mind your comment and I'll take some time to review the draft about `data-theme`. I already looked at it very quickly: it looks promising!!
